language: node_js
node_js:
  - "11.10.1"
  - '10'
  - '6'
  - '8'
cache:
  directories:
    - ~/.npm
notifications:
  email: false
script:
  - npm run test:prod && npm run build
after_success:
  - npm run travis-deploy-once "npm run report-coverage"
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run deploy-docs"; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run semantic-release"; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
